window.RENTAL_LATEST = {
  updated: "2026-08-11",
  note: "高德 500 米住宅 POI 前置筛选 + 乐有家精确小区名查询",
  rentals: [
    { id: "new-djy-dsmy-2450", name: "都市名园", station: "大剧院", distance: 306, rent: 2450, area: 20, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·小区住宅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/8TCTDHPJvucqsoyMDBFLXi.html" },
    { id: "new-djy-dsmy-2850-35", name: "都市名园", station: "大剧院", distance: 306, rent: 2850, area: 35, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·小区住宅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/A8e8GseYhohFRxo1TRC3gw.html" },
    { id: "new-djy-dsmy-2850-18", name: "都市名园", station: "大剧院", distance: 306, rent: 2850, area: 18, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·小区住宅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/6VKZTSsKqkGjzU54cUGMen.html" },
    { id: "new-djy-dsmy-2950", name: "都市名园", station: "大剧院", distance: 306, rent: 2950, area: 54, layout: "1室1厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·性价比", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/YQGRGJNqHiHytB4Kvjmt2W.html" },
    { id: "new-djy-dsmy-4500", name: "都市名园", station: "大剧院", distance: 306, rent: 4500, area: 49.19, layout: "1室1厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·上限内", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/YNEF2ygtKeRQCsuRL5WWM2.html" },
    { id: "new-djy-gdny-4200", name: "供电南苑", station: "大剧院", distance: 498, rent: 4200, area: 48, layout: "1室1厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·小区住宅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/LW9tEQvUqpv1bAYZuY4GU6.html" },
    { id: "new-djy-hlds-3500", name: "红岭大厦", station: "大剧院", distance: 453, rent: 3500, area: 45, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "B·预算正中", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/VfMQbQdf14z1PLcfnjkbps.html" },
    { id: "new-djy-hlds-3800", name: "红岭大厦", station: "大剧院", distance: 453, rent: 3800, area: 32, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "C·酒店公寓", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/KJ36SRckB2e3iPQRrJdNJ1.html" },
    { id: "new-djy-hlds-3900-35", name: "红岭大厦", station: "大剧院", distance: 453, rent: 3900, area: 35, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "C·酒店公寓", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/HU2WmXAkHNdLnRDG9i4UQw.html" },
    { id: "new-djy-hlds-3900-38", name: "红岭大厦", station: "大剧院", distance: 453, rent: 3900, area: 38, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "C·酒店公寓", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/CXoFMCWFVPUoxLknAfrddz.html" },
    { id: "new-djy-hlds-4000", name: "红岭大厦", station: "大剧院", distance: 453, rent: 4000, area: 38, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "B·普通住宅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/Efrz1NpFh2puinDWJr4bsb.html" },
    { id: "new-djy-jj100-4300", name: "京基一百大厦", station: "大剧院", distance: 166, rent: 4300, area: 31.16, layout: "1室0厅1卫", direction: "朝南", decor: "带家私家电", propertyClass: "住宅", rec: "A·地铁直连", photoCount: 4, target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/XPvVN6Do8dmWHmw7un4mgM.html" },
    { id: "new-djy-msg-4200", name: "名仕阁", station: "大剧院", distance: 125, rent: 4200, area: 40, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·近站小区", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/MEtofpjoAZKDRnCHhnpdej.html" },

    { id: "new-gm-nyds-3880-a", name: "南洋大厦", station: "国贸", distance: 191, rent: 3880, area: 35, layout: "1室0厅", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "B·近站", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/3rFYFQv8L8tnxsekWACwej.html" },
    { id: "new-gm-nyds-3880-b", name: "南洋大厦", station: "国贸", distance: 191, rent: 3880, area: 35, layout: "1室1厅", direction: "待核", decor: "待核", propertyClass: "商住楼", rec: "B·一室一厅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/3jeJmtN1empv3JZXhXe4fn.html" },
    { id: "new-gm-yzjz-4000", name: "银座金钻", station: "国贸", distance: 430, rent: 4000, area: 37.57, layout: "1室1厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·一室一厅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/TeLgAmKBRWuCrGv5LkDM9A.html" },
    { id: "new-gm-yzjz-4500", name: "银座金钻", station: "国贸", distance: 430, rent: 4500, area: 56, layout: "1室2厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·面积较大", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/4KfpBjfZKtFkZrnF4oUeZk.html" },
    { id: "new-gm-yyds-2480", name: "友谊大厦", station: "国贸", distance: 227, rent: 2480, area: 15, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·低价小户型", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/SCNS7vgoSMRD63kWsgMVqu.html" },
    { id: "new-gm-yyds-2580", name: "友谊大厦", station: "国贸", distance: 227, rent: 2580, area: 15, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·低价小户型", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/35prGQowc2cs5VMqe83Lbx.html" },
    { id: "new-gm-yyds-3000-a", name: "友谊大厦", station: "国贸", distance: 227, rent: 3000, area: 15, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·小户型", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/UtqnqoPy5L4W8WSTf7rkxG.html" },
    { id: "new-gm-yyds-3000-b", name: "友谊大厦", station: "国贸", distance: 227, rent: 3000, area: 15, layout: "1室0厅1卫", direction: "北", decor: "待核", propertyClass: "住宅小区", rec: "B·小户型", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/P2JeEpv14Dzb33EGZDhqPQ.html" },

    { id: "new-lj-dyds-3000", name: "电影大厦", station: "老街", distance: 314, rent: 3000, area: 36.87, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·预算友好", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/6FvnJZ3trWvRmmT3rDNULC.html" },
    { id: "new-lj-dyds-3380", name: "电影大厦", station: "老街", distance: 314, rent: 3380, area: 25, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·理想预算", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/EqNvrFtLgjk7JRvjoxgGcN.html" },
    { id: "new-lj-dyds-3500", name: "电影大厦", station: "老街", distance: 314, rent: 3500, area: 36.87, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·预算正中", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/CTTUrWY61aaeE5qMyEx5sC.html" },
    { id: "new-lj-dyds-3680", name: "电影大厦", station: "老街", distance: 314, rent: 3680, area: 30, layout: "1室1厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "A·一室一厅", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/5ipRAPHv9Vb1oSvwMpntHw.html" },
    { id: "new-lj-dyds-4280", name: "电影大厦", station: "老街", distance: 314, rent: 4280, area: 36.87, layout: "1室0厅1卫", direction: "待核", decor: "待核", propertyClass: "住宅小区", rec: "B·上限内", target: 3500, url: "https://shenzhen.leyoujia.com/zf/detail/5GiWX4MY7nKu8zpdmneR58.html" }
  ]
};
